mdsctl: fallback deployment (close to default); next: verify mds

diff --git a/bin/mdsctl b/bin/mdsctl
--- a/bin/mdsctl
+++ b/bin/mdsctl
@@ -303,7 +303,7 @@ installImages() {
   check ${FUNCNAME[0]}
 
   if [ "${configs[image-repository]}" ]; then
-    for i in $(docker images --filter "reference=mds-*" --format '{{ .Repository}}:{{ .Tag}}'); do
+    for i in $(docker images --filter "reference=mds-*" --format '{{.Repository}}:{{.Tag}}'); do
       # docker tag ${i} ${configs[image-repository]}/${i}
       docker push ${configs[image-repository]}/${i}
     done; unset i
@@ -652,60 +652,84 @@ installNatss() {
     (cd ${configs[natss]};
       git clone ${configs[natss-repository]} .;
       git remote add upstream ${configs[natss-repository]};
-      git remote set-url --push upstream no_push)
-      # note: bump nats-streaming version
-      # sed -i '' "s/image: nats-streaming:.*/image: nats-streaming:0.16.2/" ${configs[natss]}/natss/config/broker/natss.yaml)
+      git remote set-url --push upstream no_push)      # sed -i '' "s/image: nats-streaming:.*/image: nats-streaming:0.16.2/" ${configs[natss]}/natss/config/broker/natss.yaml)
   fi
 
-  # todo: pin to a better semaphore
-  kubectl get namespace ${configs[namespace-natss]} > /dev/null 2>&1 || {
-    installNamespace ${configs[namespace-natss]}
-
-    helm install ${configs[home]}/helm/natss --name ${configs[namespace-natss]}-nats \
-      --namespace ${configs[namespace-natss]} \
-      ${configs[values]:+$(helmOptions values ${configs[values]})} \
-      ${configs[values-natss]:+$(helmOptions values ${configs[values-natss]})} \
-      ${configs[presets]:+$(helmOptions set ${configs[presets]})} \
-      ${configs[presets-natss]:+$(helmOptions set ${configs[presets-natss]})} \
-      ${configs[sets]:+$(helmOptions set ${configs[sets]})} \
-      ${configs[sets-natss]:+$(helmOptions set ${configs[sets-natss]})} \
-      ${configs[setfiles]:+$(helmOptions set-file ${configs[setfiles]})} \
-      ${configs[setfiles-natss]:+$(helmOptions set-file ${configs[setfiles-natss]})} \
-      ${configs[dryrun]:+--dry-run --debug}
-
-    for d in $(find ${configs[natss]}/natss/cmd/* -type d -maxdepth 1 -exec sh -c 'echo $(basename {})' \;); do
-      $(docker inspect --type=image ko.local/${d} > /dev/null 2>&1) || buildNatss ${d}
-    done
-
-    helm install ${configs[home]}/helm/nats-knative --name ${configs[namespace-nats-knative]}-nats-knative \
-      # --namespace ${configs[namespace-nats-knative]} \
-      ${configs[values]:+$(helmOptions values ${configs[values]})} \
-      ${configs[values-nats-knative]:+$(helmOptions values ${configs[values-nats-knative]})} \
-      ${configs[presets]:+$(helmOptions set ${configs[presets]})} \
-      ${configs[presets-nats-knative]:+$(helmOptions set ${configs[presets-nats-knative]})} \
-      ${configs[sets]:+$(helmOptions set ${configs[sets]})} \
-      ${configs[sets-nats-knative]:+$(helmOptions set ${configs[sets-nats-knative]})} \
-      ${configs[setfiles]:+$(helmOptions set-file ${configs[setfiles]})} \
-      ${configs[setfiles-nats-knative]:+$(helmOptions set-file ${configs[setfiles-nats-knative]})} \
-      ${configs[dryrun]:+--dry-run --debug}
-    helm install ${configs[home]}/helm/nats-tenant --name ${configs[namespace-nats-tenant]}-nats-tenant \
-      --namespace ${configs[namespace-nats-tenant]} \
-      ${configs[values]:+$(helmOptions values ${configs[values]})} \
-      ${configs[values-nats-tenant]:+$(helmOptions values ${configs[values-nats-tenant]})} \
-      ${configs[presets]:+$(helmOptions set ${configs[presets]})} \
-      ${configs[presets-nats-tenant]:+$(helmOptions set ${configs[presets-nats-tenant]})} \
-      ${configs[sets]:+$(helmOptions set ${configs[sets]})} \
-      ${configs[sets-nats-tenant]:+$(helmOptions set ${configs[sets-nats-tenant]})} \
-      ${configs[setfiles]:+$(helmOptions set-file ${configs[setfiles]})} \
-      ${configs[setfiles-nats-tenant]:+$(helmOptions set-file ${configs[setfiles-nats-tenant]})} \
-      ${configs[dryrun]:+--dry-run --debug}
-
-    for cm in config-logging config-observability config-tracing; do # default-ch-webhook; do
-      # note: --export is deprecated
-      kubectl get configmap ${cm} -n knative-eventing --export -o yaml | \
-        kubectl apply -n ${configs[namespace-nats-tenant]} -f -
-    done
+  # fixme: classic install
+  kubectl get namespace natss > /dev/null 2>&1 || {
+    installNamespace natss
+    kubectl apply -n natss -f ${configs[natss]}/natss/config/broker/natss.yaml
   }
+
+  for d in $(find ${configs[natss]}/natss/cmd/* -type d -maxdepth 1 -exec sh -c 'echo $(basename {})' \;); do
+    $(docker inspect --type=image ko.local/${d} > /dev/null 2>&1) || buildNatss ${d}
+  done
+
+  for c in controller dispatcher; do
+    for t in $(docker images ko.local/channel_${c} --format '{{.Tag}}'); do
+      if [ "${t}" != "latest" ]; then
+        sed -i '' "s/image: knative.dev\/eventing-${c}\/natss\/cmd\/channel_${c}/image: ko.local\/channel_${c}:${t}/" ${configs[natss]}/natss/config/500-${c}.yaml
+        break
+      fi
+    done
+  done
+
+  # fixme: test for deployment
+  kubectl apply -f ${configs[natss]}/natss/config
+
+  # fixme: bump version
+  # sed -i '' "s/image: nats-streaming:.*/image: nats-streaming:0.16.2/" ${configs[natss]}/natss/config/broker/natss.yaml
+
+  # fixme: knative-eventing failed to resoncile with distinct namespace deployments
+  # # todo: pin to a better semaphore
+  # kubectl get namespace ${configs[namespace-natss]} > /dev/null 2>&1 || {
+  #   installNamespace ${configs[namespace-natss]}
+
+  #   helm install ${configs[home]}/helm/natss --name ${configs[namespace-natss]}-nats \
+  #     --namespace ${configs[namespace-natss]} \
+  #     ${configs[values]:+$(helmOptions values ${configs[values]})} \
+  #     ${configs[values-natss]:+$(helmOptions values ${configs[values-natss]})} \
+  #     ${configs[presets]:+$(helmOptions set ${configs[presets]})} \
+  #     ${configs[presets-natss]:+$(helmOptions set ${configs[presets-natss]})} \
+  #     ${configs[sets]:+$(helmOptions set ${configs[sets]})} \
+  #     ${configs[sets-natss]:+$(helmOptions set ${configs[sets-natss]})} \
+  #     ${configs[setfiles]:+$(helmOptions set-file ${configs[setfiles]})} \
+  #     ${configs[setfiles-natss]:+$(helmOptions set-file ${configs[setfiles-natss]})} \
+  #     ${configs[dryrun]:+--dry-run --debug}
+
+  #   for d in $(find ${configs[natss]}/natss/cmd/* -type d -maxdepth 1 -exec sh -c 'echo $(basename {})' \;); do
+  #     $(docker inspect --type=image ko.local/${d} > /dev/null 2>&1) || buildNatss ${d}
+  #   done
+
+  #   helm install ${configs[home]}/helm/nats-knative --name ${configs[namespace-nats-knative]}-nats-knative \
+  #     # --namespace ${configs[namespace-nats-knative]} \
+  #     ${configs[values]:+$(helmOptions values ${configs[values]})} \
+  #     ${configs[values-nats-knative]:+$(helmOptions values ${configs[values-nats-knative]})} \
+  #     ${configs[presets]:+$(helmOptions set ${configs[presets]})} \
+  #     ${configs[presets-nats-knative]:+$(helmOptions set ${configs[presets-nats-knative]})} \
+  #     ${configs[sets]:+$(helmOptions set ${configs[sets]})} \
+  #     ${configs[sets-nats-knative]:+$(helmOptions set ${configs[sets-nats-knative]})} \
+  #     ${configs[setfiles]:+$(helmOptions set-file ${configs[setfiles]})} \
+  #     ${configs[setfiles-nats-knative]:+$(helmOptions set-file ${configs[setfiles-nats-knative]})} \
+  #     ${configs[dryrun]:+--dry-run --debug}
+  #   helm install ${configs[home]}/helm/nats-tenant --name ${configs[namespace-nats-tfenant]}-nats-tenant \
+  #     --namespace ${configs[namespace-nats-tenant]} \
+  #     ${configs[values]:+$(helmOptions values ${configs[values]})} \
+  #     ${configs[values-nats-tenant]:+$(helmOptions values ${configs[values-nats-tenant]})} \
+  #     ${configs[presets]:+$(helmOptions set ${configs[presets]})} \
+  #     ${configs[presets-nats-tenant]:+$(helmOptions set ${configs[presets-nats-tenant]})} \
+  #     ${configs[sets]:+$(helmOptions set ${configs[sets]})} \
+  #     ${configs[sets-nats-tenant]:+$(helmOptions set ${configs[sets-nats-tenant]})} \
+  #     ${configs[setfiles]:+$(helmOptions set-file ${configs[setfiles]})} \
+  #     ${configs[setfiles-nats-tenant]:+$(helmOptions set-file ${configs[setfiles-nats-tenant]})} \
+  #     ${configs[dryrun]:+--dry-run --debug}
+
+  #   for cm in config-logging config-observability config-tracing; do # default-ch-webhook; do
+  #     # note: --export is deprecated
+  #     kubectl get configmap ${cm} -n knative-eventing --export -o yaml | \
+  #       kubectl apply -n ${configs[namespace-nats-tenant]} -f -
+  #   done
+  # }
 }
 
 testUnit() {
@@ -884,15 +908,18 @@ uninstallKnative() {
 uninstallNatss() {
   check ${FUNCNAME[0]}
 
-  helm delete --purge ${configs[namespace-natss]}-nats
-  helm delete --purge ${configs[namespace-nats-knative]}-nats-knative
-  helm delete --purge ${configs[namespace-nats-tenant]}-nats-tenant
+  kubectl delete namespace natss
+  kubectl delete -f ${configs[natss]}/natss/config
+  # fixme: knative-eventing failed to resoncile with distinct namespace deployments
+  # helm delete --purge ${configs[namespace-natss]}-nats
+  # helm delete --purge ${configs[namespace-nats-knative]}-nats-knative
+  # helm delete --purge ${configs[namespace-nats-tenant]}-nats-tenant
 
-  # fixme: deleteing a shared namespace is not right
-  for ns in ${configs[namespace-natss]} ${configs[namespace-tenant]}; do # ${configs[namespace-nats-knative]}; do
-    [ "${ns}" != "${configs[namespace-mds]}" ] && uninstallNamespace ${ns}
-  done; unset ns
-  [ -d ${configs[natss]} ] && /bin/rm -rf ${configs[natss]}
+  # # fixme: deleteing a shared namespace is not right
+  # for ns in ${configs[namespace-natss]} ${configs[namespace-tenant]}; do # ${configs[namespace-nats-knative]}; do
+  #   [ "${ns}" != "${configs[namespace-mds]}" ] && uninstallNamespace ${ns}
+  # done; unset ns
+  # [ -d ${configs[natss]} ] && /bin/rm -rf ${configs[natss]}
 }
 
 uninstallMetrics() {
